### ISSUE TITLE
Please consider the MIT License

### ISSUE THREAD

**Issue by BigBlueHat** [mikerkent/jquery-ZenCoding#1]
jQuery-ZenCoding is a great combination of two excellent libraries.

Zen-Coding recently changed their license from GPLv3 to the MIT-license:
http://twitter.com/zen_coding/status/16222899478

This change frees jQuery-ZenCoding to be re-licensed under the MIT license. A change to the MIT would make jQuery-ZenCoding compatible with an even wider range of jQuery-based projects.

Thanks in advance for considering this suggestion.

**Comment by mikerkent** [comment]
Thank you for informing me of this.  I am currently considering my options.

Ultimately I want people to be able to freely use/modify/contribute to/redistribute this software while still being able to claim it as my own.  My preference is that the licensing scheme I use should not affect whether others us this software in free or commercial projects, nor should it require (although it is always much appreciated) that credit be given.

The reason I had choosen GPLv3 was because many other Open Source I know of use it (in fact, Wikipedia claims it as the most popular overall), so I figured it would be good enough for me.  Since you have raised the issue, I am going to read through as much as I can so I fully understand both my current licensing schem, the MIT one, and maybe a few others, just for good measure, to figure out which one best suits my goals for this project.  Also, on that note, if you have any information on the licensing schemes you feel may benefit my decision, I would be happy to hear it.

If and when I decide to change or keep my license, I will surely let you know my decision and reasons.

Thanks.

**Comment by BigBlueHat** [comment]
zodoz,

Thanks for the quick and informative reply. Here are a couple of resources that I've used to learn what I know about licensing:

[Understanding Open Source and Free Software Licensing](http://oreilly.com/catalog/9780596005818/) it's also available as a [free download](http://oreilly.com/catalog/osfreesoft/book/) and of course [OpenSource.org](http://opensource.org/).

The "free-est" licenses are the one's known as "academic" ones: MIT, BSD, Apache, etc. These licenses enforce your key concern: getting credit for what you've created.

The GPL falls into another category called "copyleft" licenses which include GPL v2 & 3, AGPL, LGPL, and MPL among others. These enforce a "viral" constraint that changes made to the code also be "forced open" under the same license. Among these license the most "friendly" are the LGPL and MPL as they can be used within larger works without "infecting" them (forcing an MIT licensed project to become LGPL'ed for instance).

I highly recommend the book mentioned above for gaining a more complete understanding of open source licensing. My little right up above only scratches the surface. :)

Thank you again for the quick reply and your willingness to consider a license change.

**Comment by BigBlueHat** [comment]
Bother...I didn't mean to close this issue... :} Wish the button had said "Comment & Close this Issue" :)

**Comment by mikerkent** [comment]
I have reopened the issue.  I was also confused at first by the comment and comment+close buttons, mostly because I opened this up and thought it was an inbox message at first rather than an issue...

As for the main topic at hand, I will certainly give that book some serious attention.  Hopefully by the end of tomorrow I will have more information.  If I need more time, it will be because I am comparing/contrasting more than just these two licenses.

**Comment by mikerkent** [comment]
I think the main problem I'm trying to sort out is the "linking" issue between my software and jQuery.  jQuery is currently dual licensed under MIT and GPLv2.  As this is all related to JavaScript (which is entirely dynamic), and my code is useless without the jQuery library running on the same webpage, one could argue that I am "forced" to keep my current license (FSF stance as stated in the [GPL Wikipedia article](http://en.wikipedia.org/wiki/Gpl#Linking_and_derived_works)).  However, it could also be argued that this is a completely new work (as per Lawrence Rosen's quote in the same article), and that while it uses the jQuery library, it is not "derived" from it.

I would be interested in hearing the opinions of others on this issue.  Also, other than the "purity and openness arguments" of the different licenses, I would like to know if you have any pro/cons for what can and cannot be done with my project if licensed one way or the other.

No matter what, I will continue to research this issue and report back what I find.

Thanks.

**Comment by mikerkent** [comment]
According to [jquery.org](http://jquery.org/license), I am able to choose which license (MIT or GPLv2) of jQuery I am using for my software.  In this case I will choose MIT, and subsequently I will also license my program under MIT.

I choose MIT because it is the most open, while still allowing me to take claim over my own original software.  It is my intent that anyone should be able to use my software for any reason and with any product (commercial or not).

**Comment by BigBlueHat** [comment]
Excellent choice, zodoz, and much appreciated. I hope this gets jQuery-ZenCoding an even wider audience.
