### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by techsin** [mikerkent/jquery-ZenCoding#10]
Is this project Dead. This seems like an awesome idea. Jquery doesn't have as good way as Emmet to create html. Work should be done on this.

Doing this looks awesome .. $('body').append($.zc("h1{text}+.cont>ul>li{item$}*5"); This is 20 lines of code right there. Which could have been cluttering javascript. Sometimes you can't create templates in html and hide them.

**Comment by mikerkent** [comment]
I do not have any immediate plans for work on this project. It was started as a general purpose templating system before systems like Angular, Ember, and React existed. Since then, I've found that the combination of Jade and Angular fit my needs as a minimal HTML templating language which is easy to read, write, and gets rid of the redundant X/HTML tags.

Right now, the best use I can see if I were to move forward on this project would be as a method of compression (e.g. this format is likely smaller than most HTML and other templates, it can therefore be transmitted faster, but at the expense of unpacking on the client side). There has already been a lot of work in this space, and a balance between server side and client side rendering is being reached.

I would love to hear any other thoughts you may have. Maybe there is something I've overlooked.

Cheers.

**Comment by sukima** [comment]
Especially with ES6 template strings right around the corner and precompiler scripts like CoffeeScript, Handlebars, Bable, etc. the need for a cryptic syntax to make HTML strings is quite small these days. Emmet syntax is best for text editors I think.

**Comment by techsin** [comment]
i understand... 
I just thought doing this was pretty cool.

**Comment by mikerkent** [comment]
Please feel free to look around, explore the code, fork it, and play with it! PM me anytime with any questions you may have and I'll be more than happy to answer.
