### ISSUE TITLE
Value attribute for input elements of type submit is ignored in IE

### ISSUE THREAD

**Issue by gregopet** [mikerkent/jquery-ZenCoding#2]
If I create an input element of type 'submit' with ZenCoding and assign it a value attribute to change its text, the value is ignored and a default string is used instead in IE 8.

Here's a demo: http://jsfiddle.net/fskDS/2/

**Comment by mikerkent** [comment]
I've tried to analyze this, and right now what I can find that that IE9 is giving me an error:
SEC7112: Script from https://raw.github.com/zodoz/jquery-ZenCoding/master/jQuery-ZenCoding.js was blocked due to mime type mismatch

I'm thinking that this may mean that IE is not allowing the script to load, therefore the $.zc() function is not available.

I'll continue looking into this, and let you know what I turn up.

**Comment by mikerkent** [comment]
This particular issue appears to now be fixed. For some reason IE acts differently when calling $('<input>', attrs); than other browsers. It appears to be fixed after applying attribute changes a second time.

Line 243 if you are interested.

**Comment by gregopet** [comment]
Works now, thanks!
